version: '3.8'

services:
  nuna-db:
    image: bitnami/postgresql:latest
    container_name: nuna-db
    volumes:
      - nuna-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nuna_db
    networks:
      - nuna-network

  nuna-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuna-server
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3333
      - DATABASE_URL=postgresql://docker:docker@nuna-db:5432/nuna_db # Usando o nome do serviço como host
    depends_on:
      - nuna-db
    networks:
      - nuna-network

volumes:
  nuna-db-data:
    driver: local

networks:
  nuna-network:
    driver: bridge
