version: '3.8'

services:
  nuna-db:
    image: bitnami/postgresql:latest
    container_name: nuna-db
    volumes:
      - nuna-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nuna_db
    networks:
      - nuna-network
      
volumes:
  nuna-db-data:
    driver: local

networks:
  nuna-network:
    driver: bridge
